---
version: '2.0'

environmentTest:
  type: direct

  description: Demo workflow to access environment

  tags:
    - WFM Tutorial
    - NSP19.11

  workflow_meta:
    title:   Tutorial for expression action nsp.environment
    author:  NOKIA DEMO
    version: '1.0.0'
    license: BSD-3
    package: WFM Tutorials
    deprecated: false
    urls:
      homepage: https://github.com/nokia/nsp-workflow/tree/master/unsupported/tutorials
      repository: https://github.com/nokia/nsp-workflow
      bugs: https://github.com/nokia/nsp-workflow/issues
    dependencies:
      platform:
        nspOS: ['19.11']

  input:
    - envName: "Test Environment"
    - operation: replace
    - entries: {}

  output:
    status: done

  output-on-error:
    status: failed

  tasks:
    task1:
      action: nsp.environment
      input:
        environment: <% $.envName %>
        operation: get
      on-complete:
        - task2

    task2:
      action: nsp.environment
      input:
        environment: <% $.envName %>
        operation: <% $.operation %>
        entries: <% $.entries %>

...
