---
version: '2.0'

nsp.fakeCallout:
    description: fake callout
    base: std.echo
    base-input:
      output: {
         response: {
           data: <% $.list %>
           }
       }
    input:
     - token_auth
     - list: [
        {
          "neName": "NE1",
          "name": "1/1/1",
          "type": "SR-7750",
          "neId" : "911"
        },
        {
          "neName": "NE2",
          "name": "1/1/2",
          "type": "SR-7750",
          "neId" : "912"
        },
        {
          "neName": "NE3",
          "name": "1/1/3",
          "type": "SR-7750",
          "neId" : "913"
        },
        {
          "neName": "NE4",
          "name": "1/1/1",
          "type": "SR-7750",
          "neId" : "811"
        },
        {
          "neName": "NE4",
          "name": "2/1/2",
          "type": "SR-7750",
          "neId" : "812"
        },
        {
          "neName": "NE5",
          "name": "1/1/3",
          "type": "SR-7750",
          "neId" : "813"
        }
      ]
