---
version: '2.0'

nsp.fakeCallout2:
    description: fake callout2
    base: std.echo
    base-input:
      output: {
         response: {
           data: <% $.list %>
           }
       }
    input:
     - token_auth
     - list: [
        { "key": "Value1" },
        { "key": "Value2" },
        { "key": "Value3" }
      ]
