---
version: '2.0'

nsp.neListNFMP.fake:
  description: get list of NFMP-managed nodes (fake callout)
  base: std.echo
  base-input:
    output:
        response:
          data:
          - operState: enabled
            resyncState: done
            communicationState: up
            neName: Berlin
            description:
            managedState: managed
            adminState: unlocked
            version: 'TiMOS-B-19.5.R2 '
            location: N/A
            type: 7750-SR12
            product: 7750 SR
            sourceType: nfmp
            networkType: ip
            name: Berlin
            neId: 1.1.1.2
            ipAddress: 135.228.154.179
          - operState: enabled
            resyncState: done
            communicationState: up
            neName: Antwerp
            description:
            managedState: managed
            adminState: unlocked
            version: 'TiMOS-B-19.5.R2 '
            location: hamburg
            type: 7750-SR12
            product: 7750 SR
            sourceType: nfmp
            networkType: ip
            name: Antwerp
            neId: 1.1.1.1
            ipAddress: 135.228.149.107
  input:
   - token_auth
