version: '2.0'

sferic.transportServiceByServiceName:
  description: get transport service attributs 
  base: std.http
  base-input:
    url: http://ran-services-app.default.svc.cluster.local:8080/ran-services-app/rest/api/v1/transport-service?transportName=<% $.formValues.transportservice %>
    method: GET
    verify: /opt/nsp/os/ssl/certs/nsp/nsp.pem
    headers:
      Content-Type: application/json
      Authorization: Bearer <% $.token_auth %>
  input:
    - token_auth
    - formValues: ""
  output: <% $.content %>