---
version: '2.0'

environment:
  description: Set environment to allow portability of blueprint workflows made by Nokia
  base: std.echo
  base-input:
    output: none
  output:
    neUsername: admin
    nePassword: admin
    pkiServer: localhost
    pkiUsername: root
    pkiPassword: changeme
    pkiStorepass: 'NokiaNsp1!'
    mdmServer: localhost
    mdmUsername: root
    mdmPassword: changeme

...
